In [1]:
import numpy as np 

### The Basics

In [12]:
a = np.array([1,2,3], dtype='int16')

a

array([1, 2, 3], dtype=int16)

In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
#get dimension 
a.ndim
b.ndim

2

In [8]:
#get shape 
b.shape

(2, 3)

In [13]:
#get type 
a.dtype

dtype('int16')

In [14]:
#get size 
a.itemsize

2

In [15]:
#get total size
a.size

3

### Acessing/changing specific elements, rows, columns etc. 

In [16]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
a.shape

(2, 7)

In [21]:
#get a specific element [r,c]
a[1,5]


13

In [22]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#get a specific column 
a[:,2]

array([ 3, 10])

In [28]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [29]:
#change an element
a[1,5] = 20

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [37]:
#changing values of a specific column 
a[:,2] = [1,2]

a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 21, 14]])

### 3-D Array

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
b.shape

(2, 2, 2)

In [56]:
#get specific element(s) (work outside in | ':' = everything)

#b[0,0,1]

b[:,1,:]

array([[3, 4],
       [7, 8]])

In [59]:
# replace 
b[0,0,1] = 3
b

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
# replace multiple elements
b[:,1,0] = [9,9]

b

array([[[1, 3],
        [9, 4]],

       [[5, 6],
        [9, 8]]])

### Initializing different types of arrays 

In [71]:
# all 0s matrix 

np.zeros(5)
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [75]:
#all 1s
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
#any other number 

np.full((2,3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [78]:
# random decimal numbers (between 0 and 1)
np.random.rand(4,2,3)

array([[[0.92418933, 0.80422796, 0.46568762],
        [0.3180789 , 0.3524171 , 0.72725129]],

       [[0.54302635, 0.65668323, 0.281642  ],
        [0.45076549, 0.58609026, 0.49271679]],

       [[0.60818703, 0.11055434, 0.29515261],
        [0.47025242, 0.44166923, 0.36994577]],

       [[0.87023207, 0.68227912, 0.341567  ],
        [0.09195532, 0.88868487, 0.76447552]]])

In [87]:
#random int values
np.random.randint(3,8, size=(3,3))

array([[5, 7, 6],
       [4, 5, 7],
       [7, 3, 6]])

In [88]:
# The identity array is a square array with ones on the main diagonal.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)

r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [98]:
one = np.ones((5,5), dtype='int8')
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [100]:
zero = np.zeros((3,3), dtype ='int8')
zero[1,1] = 9 

zero

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [104]:
one[1:4,1:4] = zero 

one

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

### Copying Arrays 

In [105]:
a = np.array([1,2,3])

In [108]:
b = a.copy()

In [109]:
b

array([1, 2, 3])

### Math

In [110]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [111]:
a + 2

array([3, 4, 5, 6])

In [113]:
a -2 

array([-1,  0,  1,  2])

In [114]:
a * 2 

array([2, 4, 6, 8])

In [117]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = ([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [119]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

https://numpy.org/doc/stable/reference/routines.math.html (math functions)

In [120]:
#take the sin 

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [128]:
a = np.ones((2,3))

b = np.full((3,2),2)

c = np.matmul(a,b)
c

#alternative approach
d = a @ b 
d

array([[6., 6.],
       [6., 6.]])

### Statistics

In [131]:
stats = np.array([[1,2,3,4], 
                 [5,6,7,8]])

stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [132]:
np.min(stats)

1

In [133]:
np.max(stats)

8

In [136]:
np.max(stats, axis=1) #max row

array([4, 8])

In [137]:
np.sum(stats)

36

In [139]:
np.sum(stats, axis=0)

array([ 6,  8, 10, 12])